export type CustomerProfile = { uid: string; displayName: string; createdAt: string };
export type CustomerIdentityCandidate = {
  uid: string;
  displayName: string;
  createdAt: string;
  lastVisitAt: string | null;
  visitCount: number;
  orderCount: number;
  orderAmount: number;
};
export type CustomerIdentityCandidates = { gameId: string; items: CustomerIdentityCandidate[] };
export type CustomerHistoryOrder = { id: string; orderNumber: string; status: string; totalAmount: number };
export type CustomerVisit = {
  sessionId: string;
  customerUid: string | null;
  gameId: string;
  customerName: string;
  businessDate: string;
  businessPeriodId: string | null;
  sessionStatus: string;
  entryStatus: string;
  createdAt: string;
  recoveryCodeIssuedAt: string | null;
  recoveryCodeVersion: number;
  hasRecoveryCode: boolean;
  orderCount: number;
  orderAmount: number;
  netReceived: number;
  hasCashRecords: boolean;
  pendingDeliveryCount: number;
  gameIdVisitCount: number;
  gameIdOrderAmount: number;
  orders: CustomerHistoryOrder[];
};
export type CustomerHistoryPage = { page: number; pageSize: number; totalCount: number; items: CustomerVisit[] };
export type CustomerSummary = { visitCount: number; orderCount: number; orderAmount: number; netReceived: number; pendingDeliveryCount: number };
export type CustomerDetail = { profile: CustomerProfile; summary: CustomerSummary; visits: CustomerVisit[] };

export type DeliveryAsset = { id: string; kind: string; label: string; url: string | null; contentType: string | null; byteSize: number; createdAt: string };
export type ArtDelivery = {
  id: string;
  sessionId: string;
  customerUid: string | null;
  gameId: string;
  customerName: string;
  businessDate: string;
  orderId: string | null;
  orderNumber: string | null;
  orderItemId: string | null;
  title: string;
  description: string | null;
  status: string;
  dueDate: string | null;
  version: number;
  createdAt: string;
  updatedAt: string;
  deliveredAt: string | null;
  assets: DeliveryAsset[];
};
export type DeliveryIssued = { delivery: ArtDelivery; claimCode: string };
export type CreateDelivery = { sessionId: string; orderId: string | null; title: string; description: string | null; dueDate: string | null };
export type UpdateDelivery = { version: number; title: string; description: string | null; status: string; dueDate: string | null };
