const navigation = [
  { label: "營運操作", items: [["00", "點單管理"], ["01", "訂單列表"], ["02", "營運總覽"], ["03", "店員管理"]] },
  { label: "內容與設定", items: [["04", "菜單設定"], ["05", "活動設定"], ["06", "首頁設定"]] },
];

export default function AdminHomePreviewPage() {
  return <div className="adminTheme"><main className="adminShell adminMockShell">
    <aside className="adminTopbar"><div className="adminTopbarBrand"><span className="adminTopbarMark"><img src="/favicon.ico" alt="" /></span><span className="adminTopbarBrandCopy"><strong>清醒夢</strong><small>LUCID DREAM</small></span><button className="adminBackToSite adminBrandSiteLink" type="button">↗ 公開網站</button></div><nav className="adminNav">{navigation.map((group) => <section className="adminNavGroup" key={group.label}><p className="adminNavLabel">{group.label}</p>{group.items.map(([index, label]) => <button className={label === "營運總覽" ? "isActive" : ""} key={index} type="button"><span>{index}</span>{label}</button>)}</section>)}</nav><div className="adminTopbarUtilities"><div className="adminAccount"><div className="adminAccountIdentity"><small>目前登入</small><strong>Zero</strong><span>開發者</span></div><button className="adminButton adminButton-ghost adminThemeToggle" type="button">☾</button><button className="adminButton adminButton-ghost" type="button">登出</button></div></div></aside>
    <div className="adminWorkspace"><div className="adminContent"><section className="adminPage"><header className="adminPageHeading"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h1>營運總覽</h1><p>Zero，這裡集中顯示今日需要處理的資訊。</p></div><button className="adminButton adminButton-secondary" type="button">重新整理</button></header>
      <section className="adminOperationsOverview"><header><div><span>今日營業</span><h2>營業中</h2><p>協調接單 · 預計 01:30 結束</p></div><div className="adminOperationsActions"><button className="adminButton adminButton-primary" type="button">進入點單管理</button><button className="adminButton adminButton-secondary" type="button">查詢訂單</button></div></header><div className="adminOperationsMetrics"><article><span>等待處理</span><strong>3</strong><small>筆訂單</small></article><article><span>尚未完成</span><strong>4</strong><small>筆訂單</small></article><article><span>接單模式</span><strong className="isText">協調接單</strong><small>目前狀態</small></article><article><span>店員管理</span><strong className="isText">工作狀態</strong><button type="button">前往管理 <span>›</span></button></article></div></section>
      <section className="adminOverviewSettings"><header><h2>內容與系統設定</h2><p>低頻設定集中在這裡，不干擾現場操作。</p></header><div>{[["菜單設定", "品項、分類與價格"], ["活動設定", "活動內容與檔期"], ["首頁設定", "店舖介紹與輪播"]].map(([title, description]) => <button type="button" key={title}><strong>{title}</strong><span>{description}</span><i>›</i></button>)}</div></section>
      <div className="adminDeveloperTools"><details className="adminDeveloperDisclosure"><summary className="adminDeveloperDisclosureSummary"><span><b>帳號安全工具</b><small>取得註冊金鑰，或協助後台使用者重設帳號。</small></span><i>⌄</i></summary></details><details className="adminDeveloperDisclosure"><summary className="adminDeveloperDisclosureSummary"><span><b>進階管理工具</b><small>公開頁面顯示狀態與使用者帳號列表。</small></span><i>⌄</i></summary></details></div>
    </section></div></div>
  </main></div>;
}
